<li class="m-b-md anim_emt b_to_t_scale">
  <a href="[field:arcurl/]" class="trans" data-postid="57" style="height:240px">
        <div class="pics coverbg" style="background-image:url({dede:global.cfg_cmsurl/}/static/images/img_main_1.png);float:left">
     [field:image/]     
    </div>  
    <div class="info" style="position:absolute;width:50%;left:50%">
          <div style="padding:30px"> 
             <h4 class="date c-gray m-b-xs" style="float:left;">[field:shorttitle function='cn_substr(@me,40)'/]　　&mdash;&mdash;　　</h4><br><br>
             <h5 style="float:left;color:#333333;font-size:28px">[field:title/]</h5>      
             <br>
             <p style="font-size:16px">

               <!-- [field:id runphp='yes'] $aid = @me; $row = $GLOBALS['dsql']->GetOne("Select body From `dede_addonarticle` where aid='$aid' "); @me = cn_substr(strip_tags("{$row['body']}"),960);[/field:id] --></p>
            </div>            
 </div>
 
  </a>
</li>