
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phone itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>


<field:address itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:remark itemname="备注" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:remark>
