<?php  exit();
/*
Page: /dede/diy_add.php?action=add
Error: Erreur de syntaxe près de '-assi' à la ligne 1 <br />Error sql: <font color='red'>SHOW TABLES FROM d-assi </font>
Time2016-12-09 10:38:44
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_addonarticle' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_addonarticle</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_addonimages' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_addonimages</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_addoninfos' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_addoninfos</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_addonshop' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_addonshop</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_addonsoft' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_addonsoft</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_addonspec' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_addonspec</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_admin' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_admin</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_admintype' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_admintype</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_advancedsearch' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_advancedsearch</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_arcatt' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_arcatt</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_arccache' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_arccache</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_archives' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_archives</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_arcmulti' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_arcmulti</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_arcrank' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_arcrank</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_arctiny' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_arctiny</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_arctype' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_arctype</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_area' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_area</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_channeltype' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_channeltype</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_co_htmls' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_co_htmls</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_co_mediaurls' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_co_mediaurls</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_co_note' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_co_note</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_co_onepage' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_co_onepage</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_co_urls' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_co_urls</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_diyform1' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_diyform1</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_diyforms' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_diyforms</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_dl_log' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_dl_log</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_downloads' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_downloads</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_erradd' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_erradd</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_feedback' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_feedback</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_flink' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_flink</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_flinktype' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_flinktype</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_freelist' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_freelist</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_homepageset' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_homepageset</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_keywords' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_keywords</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_log' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_log</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_company' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_company</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_feed' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_feed</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_flink' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_flink</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_friends' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_friends</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_group' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_group</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_guestbook' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_guestbook</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_model' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_model</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_msg' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_msg</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_operation' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_operation</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_person' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_person</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_pms' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_pms</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_snsmsg' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_snsmsg</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_space' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_space</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_stow' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_stow</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_stowtype' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_stowtype</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_tj' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_tj</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_type' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_type</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_member_vhistory' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_member_vhistory</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_moneycard_record' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_moneycard_record</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_moneycard_type' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_moneycard_type</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_mtypes' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_mtypes</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_multiserv_config' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_multiserv_config</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_myad' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_myad</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_myadtype' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_myadtype</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_mytag' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_mytag</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_payment' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_payment</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_plus' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_plus</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_plus_seoinfo' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_plus_seoinfo</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_purview' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_purview</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_pwd_tmp' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_pwd_tmp</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_ratings' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_ratings</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_scores' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_scores</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_search_cache' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_search_cache</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_search_keywords' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_search_keywords</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sgpage' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sgpage</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_shops_delivery' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_shops_delivery</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_shops_orders' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_shops_orders</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_shops_products' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_shops_products</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_shops_userinfo' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_shops_userinfo</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_softconfig' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_softconfig</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sphinx' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sphinx</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_stepselect' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_stepselect</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sys_enum' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sys_enum</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sys_module' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sys_module</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sys_set' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sys_set</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sys_task' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sys_task</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_sysconfig' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_sysconfig</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_tagindex' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_tagindex</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_taglist' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_taglist</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_uploads' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_uploads</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_verifies' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_verifies</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_vote' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_vote</font>
Time2016-12-10 15:26:23
*/
?>
<?php  exit();
/*
Page: /dede/sys_data_done.php?dopost=bak
Error: Erreur de syntaxe près de '-assi.dede_vote_member' à la ligne 1 <br />Error sql: <font color='red'>SHOW CREATE TABLE d-assi.dede_vote_member</font>
Time2016-12-10 15:26:23
*/
?>
